// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProfile(arg1:string):Promise<string>;

export function ClearActivity():Promise<void>;

export function CreateInvite(arg1:string):Promise<string>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DisconnectNow():Promise<void>;

export function GetActivity(arg1:number):Promise<Array<main.ActivityEntry>>;

export function GetActivityBefore(arg1:number,arg2:number):Promise<Array<main.ActivityEntry>>;

export function GetClientName():Promise<string>;

export function GetState():Promise<main.State>;

export function ImportConfig(arg1:string):Promise<main.State>;

export function InviteLink(arg1:string):Promise<string>;

export function ListClients():Promise<Array<main.ClientInfo>>;

export function ListProfiles():Promise<Array<main.ProfileInfo>>;

export function ManagerConnect(arg1:string):Promise<void>;

export function ManagerDisconnect(arg1:string):Promise<void>;

export function ManagerState():Promise<main.ManagerStateView>;

export function QRImage(arg1:string):Promise<string>;

export function RemoveClient(arg1:string):Promise<void>;

export function Revoke(arg1:boolean):Promise<void>;

export function SelfRegister(arg1:string,arg2:string):Promise<main.State>;

export function SetAutostart(arg1:boolean):Promise<main.State>;

export function SetClientDisabled(arg1:string,arg2:boolean):Promise<void>;

export function SetClientName(arg1:string):Promise<void>;

export function SetName(arg1:string):Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function TestProfile(arg1:string):Promise<string>;
