// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['main']['App']['AddProfile'](arg1);
}

export function ClearActivity() {
  return window['go']['main']['App']['ClearActivity']();
}

export function CreateInvite(arg1) {
  return window['go']['main']['App']['CreateInvite'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DisconnectNow() {
  return window['go']['main']['App']['DisconnectNow']();
}

export function GetActivity(arg1) {
  return window['go']['main']['App']['GetActivity'](arg1);
}

export function GetActivityBefore(arg1, arg2) {
  return window['go']['main']['App']['GetActivityBefore'](arg1, arg2);
}

export function GetClientName() {
  return window['go']['main']['App']['GetClientName']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function InviteLink(arg1) {
  return window['go']['main']['App']['InviteLink'](arg1);
}

export function ListClients() {
  return window['go']['main']['App']['ListClients']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ManagerConnect(arg1) {
  return window['go']['main']['App']['ManagerConnect'](arg1);
}

export function ManagerDisconnect(arg1) {
  return window['go']['main']['App']['ManagerDisconnect'](arg1);
}

export function ManagerState() {
  return window['go']['main']['App']['ManagerState']();
}

export function QRImage(arg1) {
  return window['go']['main']['App']['QRImage'](arg1);
}

export function RemoveClient(arg1) {
  return window['go']['main']['App']['RemoveClient'](arg1);
}

export function Revoke(arg1) {
  return window['go']['main']['App']['Revoke'](arg1);
}

export function SelfRegister(arg1, arg2) {
  return window['go']['main']['App']['SelfRegister'](arg1, arg2);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetClientDisabled(arg1, arg2) {
  return window['go']['main']['App']['SetClientDisabled'](arg1, arg2);
}

export function SetClientName(arg1) {
  return window['go']['main']['App']['SetClientName'](arg1);
}

export function SetName(arg1) {
  return window['go']['main']['App']['SetName'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function TestProfile(arg1) {
  return window['go']['main']['App']['TestProfile'](arg1);
}
